/**
 * Prisma Migrate without native engine binaries.
 *
 * Runs Prisma's own schema engine compiled to WebAssembly
 * (`@prisma/schema-engine-wasm`) over the `@prisma/adapter-pg` driver. It
 * produces exactly the SQL and `_prisma_migrations` bookkeeping that
 * `prisma migrate` does, for environments that can't download
 * binaries.prisma.sh (locked-down CI, sandboxes, some corporate networks).
 *
 *   tsx scripts/migrate-wasm.ts create --name <name>   # like `prisma migrate dev --create-only`
 *   tsx scripts/migrate-wasm.ts deploy                  # like `prisma migrate deploy`
 *   tsx scripts/migrate-wasm.ts diff                    # pending SQL (stdout), no files written
 *
 * The WASM engine can't introspect a live Postgres through the JS driver yet
 * (it fails on `"char"` catalog columns), so `create` diffs two datamodels
 * instead of replaying migrations on a shadow database: the schema as of the
 * last migration is kept in `prisma/migrations/schema.snapshot.prisma`.
 * CI cross-checks migrations against the schema with the native engine.
 *
 * All commands need DIRECT_URL or DATABASE_URL: the engine connects on start.
 * `create` and `diff` read nothing from that database.
 */
import "../load-env";

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PrismaPg } from "@prisma/adapter-pg";
import { bindMigrationAwareSqlAdapterFactory } from "@prisma/driver-adapter-utils";
import { SchemaEngine, type MigrationList } from "@prisma/schema-engine-wasm";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = path.join(root, "prisma", "schema");
const migrationsDir = path.join(root, "prisma", "migrations");
const lockfilePath = path.join(migrationsDir, "migration_lock.toml");
const LOCKFILE = `# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
`;
const snapshotPath = path.join(migrationsDir, "schema.snapshot.prisma");
const filters = { externalTables: [], externalEnums: [] };

function connectionConfig() {
  const raw = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
  if (!raw) throw new Error("Set DIRECT_URL or DATABASE_URL (any reachable PostgreSQL)");
  const url = new URL(raw);
  // Structured config (not connectionString) so a shadow database name can be
  // substituted safely (pg lets connectionString override `database`).
  return {
    host: url.hostname,
    port: Number(url.port || 5432),
    user: decodeURIComponent(url.username),
    password: decodeURIComponent(url.password),
    database: url.pathname.replace(/^\//, "") || "postgres",
    ssl: url.searchParams.get("sslmode") === "require" ? { rejectUnauthorized: false } : undefined,
  };
}

function schemaFiles() {
  return readdirSync(schemaDir)
    .filter((f) => f.endsWith(".prisma"))
    .sort()
    .map((f) => ({
      path: path.join(schemaDir, f),
      content: readFileSync(path.join(schemaDir, f), "utf8"),
    }));
}

/** All schema files as one datamodel (generator/datasource blocks appear once in _base.prisma). */
function combinedSchema(): string {
  return schemaFiles()
    .map((f) => `// ── ${path.basename(f.path)}\n${f.content.trimEnd()}\n`)
    .join("\n");
}

function migrationsList(): MigrationList {
  const dirs = existsSync(migrationsDir)
    ? readdirSync(migrationsDir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
    : [];
  return {
    baseDir: migrationsDir,
    lockfile: {
      path: "migration_lock.toml",
      content: existsSync(lockfilePath) ? readFileSync(lockfilePath, "utf8") : null,
    },
    shadowDbInitScript: "",
    migrationDirectories: dirs.map((name) => {
      const file = path.join(migrationsDir, name, "migration.sql");
      return {
        path: name,
        migrationFile: {
          path: "migration.sql",
          content: existsSync(file)
            ? { tag: "ok" as const, value: readFileSync(file, "utf8") }
            : { tag: "error" as const, value: `missing ${file}` },
        },
      };
    }),
  };
}

/**
 * Adapter factory whose shadow database is always cleaned up: the stock
 * factory drops it while its pool is still connected, which Postgres refuses.
 */
function adapterFactory() {
  const config = connectionConfig();
  const base = new PrismaPg(config);
  return {
    provider: base.provider,
    adapterName: base.adapterName,
    connect: () => base.connect(),
    async connectToShadowDb() {
      const admin = await base.connect();
      const name = `prisma_migrate_shadow_db_${crypto.randomUUID().replaceAll("-", "")}`;
      await admin.executeScript(`CREATE DATABASE "${name}"`);
      const shadow = await new PrismaPg({ ...config, database: name }).connect();
      const dispose = shadow.dispose.bind(shadow);
      shadow.dispose = async () => {
        await dispose();
        await admin.executeScript(`DROP DATABASE IF EXISTS "${name}" WITH (FORCE)`);
        await admin.dispose();
      };
      return shadow;
    },
  };
}

async function engine(): Promise<SchemaEngine> {
  const factory = bindMigrationAwareSqlAdapterFactory(adapterFactory());
  const files = schemaFiles();
  return SchemaEngine.new(
    { datamodels: files.map((f) => [f.path, f.content] as [string, string]) },
    () => undefined,
    factory,
  );
}

function timestamp(d = new Date()): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}

async function main() {
  const [command, ...rest] = process.argv.slice(2);
  const nameIdx = rest.indexOf("--name");
  const name = (nameIdx >= 0 ? rest[nameIdx + 1] : undefined) ?? "change";

  const e = await engine();
  try {
    if (command === "deploy") {
      const { appliedMigrationNames } = await e.applyMigrations({
        migrationsList: migrationsList(),
        filters,
      });
      console.warn(
        appliedMigrationNames.length
          ? `Applied ${appliedMigrationNames.length} migration(s): ${appliedMigrationNames.join(", ")}`
          : "No pending migrations.",
      );
      return;
    }
    if (command === "diff" || command === "create") {
      const hasMigrations = migrationsList().migrationDirectories.length > 0;
      if (hasMigrations && !existsSync(snapshotPath)) {
        throw new Error(`${path.relative(root, snapshotPath)} is missing; restore it from git.`);
      }
      const res = await e.diff({
        from: hasMigrations
          ? {
              tag: "schemaDatamodel",
              files: [{ path: snapshotPath, content: readFileSync(snapshotPath, "utf8") }],
            }
          : { tag: "empty" },
        to: { tag: "schemaDatamodel", files: schemaFiles() },
        script: true,
        exitCode: null,
        filters,
      });
      const pending = res.stdout.replace(/^-- This is an empty migration\.\s*$/m, "").trim();
      if (command === "diff") {
        process.stdout.write(pending ? `${pending}\n` : "");
        return;
      }
      if (!/^[a-z0-9_]+$/.test(name)) throw new Error("--name must be snake_case");
      if (!pending) {
        console.warn("Schema and migrations are in sync — nothing to create.");
        return;
      }
      const dir = path.join(migrationsDir, `${timestamp()}_${name}`);
      mkdirSync(dir, { recursive: true });
      writeFileSync(path.join(dir, "migration.sql"), `${pending}\n`);
      writeFileSync(snapshotPath, combinedSchema());
      if (!existsSync(lockfilePath)) writeFileSync(lockfilePath, LOCKFILE);
      console.warn(`Created ${path.relative(root, dir)}/migration.sql`);
      return;
    }
    throw new Error(
      `Unknown command "${command ?? ""}". Use create --name <name> | deploy | diff.`,
    );
  } finally {
    e.free();
  }
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
